name: Build LaTeX PDF

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required for deleting/creating releases

    steps:
      # 1) Checkout ----------------------------------------------------
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # good practice for release steps

      # 2) Compile -----------------------------------------------------
      - name: Compile kandi.tex
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: kandi.tex
          latexmk_use_xelatex: true

      # 3) Upload artifact ---------------------------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kandi-pdf
          path: src/kandi.pdf

      # 4) Update the "latest" release --------------------------------
      - name: Delete previous 'latest' release
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true   # don't fail if no prior release exists

      - name: Create / update 'latest' release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Compiled PDF (latest)
          artifacts: src/kandi.pdf
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
